// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetCoordinationStatuses() {
  return window['go']['main']['App']['GetCoordinationStatuses']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchMultiAgentDemo() {
  return window['go']['main']['App']['LaunchMultiAgentDemo']();
}

export function NewAgent(arg1) {
  return window['go']['main']['App']['NewAgent'](arg1);
}

export function NewNamedAgent(arg1, arg2) {
  return window['go']['main']['App']['NewNamedAgent'](arg1, arg2);
}

export function PTYKill(arg1) {
  return window['go']['main']['App']['PTYKill'](arg1);
}

export function PTYList() {
  return window['go']['main']['App']['PTYList']();
}

export function PTYSpawn(arg1) {
  return window['go']['main']['App']['PTYSpawn'](arg1);
}

export function PTYWrite(arg1, arg2) {
  return window['go']['main']['App']['PTYWrite'](arg1, arg2);
}

export function RespondToApproval(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RespondToApproval'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}
