// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAgents():Promise<Array<main.AgentSession>>;

export function GetCoordinationStatuses():Promise<Array<main.CoordinationStatus>>;

export function GetVersion():Promise<string>;

export function LaunchMultiAgentDemo():Promise<Array<string>>;

export function NewAgent(arg1:string):Promise<string>;

export function NewNamedAgent(arg1:string,arg2:string):Promise<string>;

export function PTYKill(arg1:string):Promise<void>;

export function PTYList():Promise<Array<string>>;

export function PTYSpawn(arg1:string):Promise<string>;

export function PTYWrite(arg1:string,arg2:string):Promise<void>;

export function RespondToApproval(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;
